{% set name = "deepface" %}
{% set version = "0.0.93" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepface-{{ version }}.tar.gz
  sha256: 7f5fc6306a3a07ee6c529b03571e64fe53d9f259e1d4091f5e28386264962b92

build:
  entry_points:
    - deepface = deepface.DeepFace:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - requests >=2.27.1
    - numpy >=1.14.0
    - pandas >=0.23.4
    - gdown >=3.10.1
    - tqdm >=4.30.0
    - pillow >=5.2.0
    - opencv-python >=4.5.5.64
    - tensorflow >=1.9.0
    - keras >=2.2.0
    - flask >=1.1.2
    - flask_cors >=4.0.1
    - mtcnn >=0.1.0
    - retina-face >=0.0.1
    - fire >=0.4.0
    - gunicorn >=20.1.0

test:
  imports:
    - deepface
  commands:
    - deepface --help
  # Upstream uses python-opencv which is a wrapper around opencv which is provided by conda-forge already.
  # This has a slightly different version though which is why pip check fails.

about:
  home: https://github.com/serengil/deepface
  summary: A Lightweight Face Recognition and Facial Attribute Analysis Framework (Age, Gender, Emotion, Race) for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - serengil
    - BastianZim
