{% set name = "deepface" %}
{% set version = "0.0.81" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepface-{{ version }}.tar.gz
  sha256: c0212fb5b867ed4f460784c9a3008243b9eb8bb26578140f1aebcd0a7c9c97a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - deepface = deepface.DeepFace:cli
  number: 0

requirements:
  host:
    - python >=3.5.5
    - pip
  run:
    - python >=3.5.5
    - numpy >=1.14.0
    - pandas >=0.23.4
    - gdown >=3.10.1
    - tqdm >=4.30.0
    - pillow >=5.2.0
    - opencv >=4.5.5.64
    - tensorflow >=1.9.0
    - keras >=2.2.0
    - flask >=1.1.2
    - mtcnn >=0.1.0
    - retina-face >=0.0.1
    - fire >=0.4.0
    - gunicorn >=20.1.0
    - deprecated >=1.2.13

test:
  imports:
    - deepface
  commands:
    - pip check
    - deepface --help
  requires:
    - pip

about:
  home: https://github.com/serengil/deepface
  summary: A Lightweight Face Recognition and Facial Attribute Analysis Framework (Age, Gender, Emotion, Race) for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - serengil
    - BastianZim
