{% set name = "deepface" %}
{% set version = "0.0.78" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepface-{{ version }}.tar.gz
  sha256: e1c5c1ab8add6bfc891667dc6802ec6f172b9f4588e01b7dd44622fb934de6c7

build:
  entry_points:
    - deepface = deepface.DeepFace:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]
  # https://github.com/serengil/deepface/issues/486

requirements:
  host:
    - pip
    - python
  run:
    - fire >=0.4.0
    - flask >=1.1.2
    - gdown >=3.10.1
    - keras >=2.2.0
    - mtcnn >=0.1.0
    - numpy >=1.14.0
    - opencv >=4.5.5
    - pandas >=0.23.4
    - pillow >=5.2.0
    - python
    - retina-face >=0.0.1
    - tensorflow >=1.9.0
    - tqdm >=4.30.0

test:
  imports:
    - deepface
  commands:
    - deepface --help
  # Upstream uses python-opencv which is a wrapper around opencv which is provided by conda-forge already.
  # This has a slightly different version though which is why pip check fails.

about:
  home: https://github.com/serengil/deepface
  summary: A Lightweight Face Recognition and Facial Attribute Analysis Framework (Age, Gender, Emotion, Race) for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - serengil
    - BastianZim
